### ISSUE TITLE
Use platform specific packaging with `vsce` to ship optimized ruff wheels.

### ISSUE THREAD

**Issue by karthiknadig** [charliermarsh/vscode-ruff#12]

**Comment by charliermarsh** [comment]
Thanks @karthiknadig! Is the current setup not shipping platform-specific builds?

**Comment by karthiknadig** [comment]
This is all I see on windows, as you can see it does not really have the ruff package just the info for it.
![image](https://user-images.githubusercontent.com/3840081/201219378-67f9ce17-6f87-43e9-8971-f30b4dcf8656.png)

Basically the complied bits are not included. This is intentional with the default packaging that i set up nox with in the template. It pulls only source packages and not compiled bits. This way i could just ship a single version for all cases.

I ran into a similar issue with black on python 3.7, where it specifically uses compiled typed_ast. So, I made a script to create a composite package with all the bits for all platforms, and let python deal with picking the right thing. see here: https://github.com/microsoft/vscode-black-formatter/blob/5abe6ae931331172ccd8697b9d5a2fb40eeb8734/noxfile.py#L269

but in your case, I would optimize the package size as well, by building platform specific VSIX for each of the supported VSIX platforms. Build a composite package for that specific platform.

**Comment by karthiknadig** [comment]
Currently this fails on windows with:
```
ruff --no-cache --format json - --stdin-filename c:\GIT\repro\mypytest\simple.py
CWD Server: c:\GIT\repro\mypytest
Failed to handle user defined notification "textDocument/didOpen": (DidOpenTextDocumentParams(text_document=TextDocumentItem(uri='file:///c%3A/GIT/repro/mypytest/simple.py', language_id='python', version=1, text="x: int = 'a'")),)
Traceback (most recent call last):
  File "c:\Users\kanadig\.vscode\extensions\charliermarsh.ruff-2022.0.6\bundled\libs\pygls\protocol.py", line 77, in decorator
    self._execute_notification(user_func, *args, **kwargs)
  File "c:\Users\kanadig\.vscode\extensions\charliermarsh.ruff-2022.0.6\bundled\libs\pygls\protocol.py", line 223, in _execute_notification
    handler(*params)
  File "c:\Users\kanadig\.vscode\extensions\charliermarsh.ruff-2022.0.6\bundled\tool\server.py", line 75, in did_open
    diagnostics: list[lsp.Diagnostic] = _linting_helper(document)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kanadig\.vscode\extensions\charliermarsh.ruff-2022.0.6\bundled\tool\server.py", line 104, in _linting_helper
    result = _run_tool_on_document(document, use_stdin=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kanadig\.vscode\extensions\charliermarsh.ruff-2022.0.6\bundled\tool\server.py", line 316, in _run_tool_on_document
    result = utils.run_path(
             ^^^^^^^^^^^^^^^
  File "c:\Users\kanadig\.vscode\extensions\charliermarsh.ruff-2022.0.6\bundled\tool\utils.py", line 148, in run_path
    with subprocess.Popen(
         ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.240.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.240.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by charliermarsh** [comment]
Interesting... I thought I was building platform-specific extensions via this [Workflow](https://github.com/charliermarsh/vscode-ruff/blob/main/.github/workflows/release.yaml). I'm definitely _intending_ to build for macOS, Windows, etc. I think it's working for macOS? This is what I see when I unzip the extension from the Marketplace:

![Screen Shot 2022-11-10 at 5 47 45 PM](https://user-images.githubusercontent.com/1309177/201222202-b38fefd5-40c0-42e3-93dc-c80024692765.png)

**Comment by charliermarsh** [comment]
And on Windows, it does seem to be downloading the wheel:

![Screen Shot 2022-11-10 at 5 49 21 PM](https://user-images.githubusercontent.com/1309177/201222398-39973a75-8749-47df-87f2-38dfa43e59a4.png)

So I'm not sure why it's not included in the published bundle. Any ideas?

**Comment by karthiknadig** [comment]
I am suspecting that `vsce` is probably ignoring it for some reason. I checked the `.vscodeignore` it seems to be correct. May be running it verbose might give some clue on why it was ignored.

Also for `ruff` on pypi, I think you can package `ruff` in an importable way. It may not expose anything other than running `main` but that would allow `import ruff` and you coudld have platform specific *.so / *.dll for ruff.

**Comment by charliermarsh** [comment]
Any tips on enabling verbose logging? Not seeing any flags or env vars.

**Comment by charliermarsh** [comment]
It does look like it's including the `.exe` file. Does `vsce` filter those out or something?

![Screen Shot 2022-11-10 at 7 06 58 PM](https://user-images.githubusercontent.com/1309177/201231802-722ada2c-63f0-4c77-ad66-83ecc4882f1c.png)

**Comment by charliermarsh** [comment]
(It's possible that the extension _code_ is wrong and I need to use `ruff.exe` as the binary? But I don't understand why it wouldn't appear in your screenshot in that case.)

**Comment by charliermarsh** [comment]
I think something must've regressed here because older versions supported all platforms:

![Screen Shot 2022-11-10 at 7 12 04 PM](https://user-images.githubusercontent.com/1309177/201232411-99f66bd3-8c33-457e-9c7f-d027c09a2c83.png)

**Comment by charliermarsh** [comment]
Ah, ok. I had enabled `--skip-duplicate` to make the action idempotent (so that if one binary failed to publish, I could re-run the failed task). But it looks like `vsce` doesn't take different targets into account, and treats each target as a duplicate? That feels like a `vsce` bug, though maybe I'm misunderstanding.

![Screen Shot 2022-11-10 at 7 15 57 PM](https://user-images.githubusercontent.com/1309177/201232797-20f7d805-5154-4a77-b881-89389b835deb.png)

**Comment by charliermarsh** [comment]
Ok, I believe this is fixed, thanks.

![Screen Shot 2022-11-10 at 7 24 34 PM](https://user-images.githubusercontent.com/1309177/201233746-8b95ac75-a845-42b4-9f79-796b2050781b.png)
