### ISSUE TITLE
Upgrade to ruff 0.0.116

### ISSUE THREAD

**Issue by brettcannon** [charliermarsh/vscode-ruff#16]
It would be great to get the isort warnings that seem to post-date 0.0.109 that ships with the extension.

**Comment by charliermarsh** [comment]
Will release a new version once [v0.0.117](https://github.com/charliermarsh/ruff/releases/tag/v0.0.117) is up (building now)!

**Comment by charliermarsh** [comment]
Fixed in 2022.0.13.
