### ISSUE TITLE
Enable code action for fixable lint errors

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/vscode-ruff#2]

**Comment by DataHearth** [comment]
Hey! I've seen your recent commits and PRs that include the `Code Action` and `Organize imports` options for the extension ([changelog](https://github.com/charliermarsh/vscode-ruff/commit/a55185cb49443570e344d6e367484a0201e980a0) for those who wants 🙂 ).
Do you plan to do a new release soon ? This is my most anticipated feature within the extension ! 

Thank you for your hard work 👍 !

**Comment by charliermarsh** [comment]
@DataHearth - Yeah, I'm cutting it now!

**Comment by charliermarsh** [comment]
The Marketplace page hasn't updated yet, but I've confirmed locally that `2022.0.18` is live and includes a lot of these behaviors :)
