### ISSUE TITLE
vscode-ruff crashes if used with Python 3.7

### ISSUE THREAD

**Issue by sgryjp** [charliermarsh/vscode-ruff#43]
As of v2022.0.18, vscode-ruff is [using warlus operator](https://github.com/charliermarsh/vscode-ruff/blob/2022.0.18/bundled/tool/server.py#L258). Because the operator is supported in Python 3.8 or later, vscode-ruff crashes if we open a project using Python 3.7 or older.

Since [Python 3.7 is still supported](https://endoflife.date/python), it would be great if vscode-ruff also supports running on Python 3.7 too.

**Comment by charliermarsh** [comment]
Ah sorry, total oversight on my part. Will fix in a few mins and publish an updated release.

**Comment by charliermarsh** [comment]
Yet another reason to setup CI with multi-version testing!

**Comment by charliermarsh** [comment]
[2022.0.19](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff) is out now.

**Comment by sgryjp** [comment]
Now it works. Thank you!
