### ISSUE TITLE
Avoid highlighting the entire source code block of a function / class if it violates a rule about the function / class as a whole

### ISSUE THREAD

**Issue by kelvindecosta** [charliermarsh/vscode-ruff#56]
## Overview

Currently, if `ruff` finds an issue with a function / class, say, if it is too complex (`mccabe`) or if it is missing a docstring, `vscode-ruff` underlines the entire block of text that represents the violation object.

This behavior makes it difficult to check if there are other issues within the function / class code block.

## Suggested Solutions

- Underlining only the violating code block's keyword, i.e., `def` for functions and `class` for classes
- Underlining the function signature

**Comment by charliermarsh** [comment]
I believe this was fixed by @harupy in a very recent release! I’ll cut a new release of the plugin today hopefully.

**Comment by charliermarsh** [comment]
Yeah this makes sense. I need to see how other linters handle this.

**Comment by charliermarsh** [comment]
(Thanks for the clear issue.)

**Comment by charliermarsh** [comment]
This is being tracked upstream as https://github.com/charliermarsh/ruff/issues/1246.

**Comment by charliermarsh** [comment]
Should be fixed in the next release via https://github.com/charliermarsh/ruff/pull/1247.
